### ISSUE TITLE
[Guider] GitHub Pages workflow is invalid

### ISSUE THREAD

**Issue by jonbarrow** [mrjvs/neatojs#29]
### Describe the bug

The documentation on how to deploy to GitHub Pages (https://neatojs.com/docs/guider/guides/deploy/github-pages) uses an invalid workflow. The `Upload` step uses both `working-directory` and `uses`, which according to [this comment](https://github.com/cypress-io/github-action/issues/68#issuecomment-577790752) on another issue is invalid. This causes the deployment to fail. Screenshot:

![Screenshot from 2024-03-19 10-22-41](https://github.com/mrjvs/neatojs/assets/27011796/51c83014-e404-4a60-8eda-528908b78cf2)

### Which package/app is affected (leave empty if unsure)

Guider

### Steps to reproduce

Deploy using the current workflow

### Expected Behavior

To not fail

**Comment by mrjvs** [comment]
I'll fix, in the meantime, you can remove the line that causing it to fail, with your configuration it shouldn't be needed. (the defaults will work)

**Comment by mrjvs** [comment]
Fixed in latest feature branch, will be published soon:tm:
